name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DOTNET_VERSION: '8.0.x'
  AZURE_RESOURCE_GROUP: 'rg-order-processing'
  REGISTRY_NAME: 'orderscruzlpsmouiyo6a'

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build OrderApi
        run: dotnet build src/OrderApi/OrderApi.csproj --configuration Release

      - name: Build FraudChecker
        run: dotnet build src/FraudChecker/FraudChecker.csproj --configuration Release

      - name: Build OrderWorker
        run: dotnet build src/OrderWorker/OrderWorker.csproj --configuration Release

  deploy-functions:
    name: Deploy Azure Functions
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Publish OrderApi
        run: dotnet publish src/OrderApi/OrderApi.csproj -c Release -o ./publish/OrderApi

      - name: Deploy OrderApi
        run: |
          cd ./publish/OrderApi
          zip -r ../../orderapi.zip .
          cd ../..
          az functionapp deployment source config-zip \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --name orders-dev-api-q7x2 \
            --src orderapi.zip

      - name: Publish FraudChecker
        run: dotnet publish src/FraudChecker/FraudChecker.csproj -c Release -o ./publish/FraudChecker

      - name: Deploy FraudChecker
        run: |
          cd ./publish/FraudChecker
          zip -r ../../fraudchecker.zip .
          cd ../..
          az functionapp deployment source config-zip \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --name orders-dev-fraud \
            --src fraudchecker.zip

  build-push-container:
    name: Build & Push Dock